name: Packaging pipeline
run-name: Package the new version of the application
on:
  push:
    tags:
      - '*.*.*'  # Match versions like 1.0.0, 2.3.4, etc.
  workflow_dispatch:
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0  # Fetch all history for all branches and tags
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '8.0.x'
            - name: Get latest tag
              id: get_tag
              uses: actions-ecosystem/action-get-latest-tag@v1
            - name: Install NuGet CLI
              run: |
                  wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -O nuget.exe
            - name: Build the project
              run: dotnet build RegUI.sln --configuration Release
            - name: Publish the app
              run: dotnet publish ./RegUI.csproj --configuration Release --self-contained true --output ./output_dir
            - name: Create nuget package
              run: nuget pack ./RegUI/RegUI.nuspec -OutputDirectory ./out
              # make installer with squirrel
            - name: Create installer
              run: |
                  nuget install Squirrel -Version 2.0.1 -OutputDirectory tools
                  .\tools\Squirrel.2.0.1\tools\squirrel --releasify .\out\RegUI${{ steps.get_tag.outputs.tag }}.nupkg --releaseDir .\Releases
            - name: Upload Release Asset
              uses: actions/upload-artifact@v4
              with:
                  name: RegUI-Setup
                  path: .\Releases